"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 12:35:07.897304
"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import context

from app.config import get_settings
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def _dim() -> int:
    return int(context.config.attributes.get("embedding_dim") or get_settings().embedding_dim)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('input_type', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('sitemap_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('claims',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.Text(), nullable=False),
    sa.Column('claim_key', sa.Text(), nullable=False),
    sa.Column('text_original', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_keys', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=_dim()), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_check_id'), 'claims', ['check_id'], unique=False)
    op.create_index('ix_claims_embedding', 'claims', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_claims_entity_keys', 'claims', ['entity_keys'], unique=False, postgresql_using='gin')
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('stage_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('check_id', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_runs_check_id'), 'stage_runs', ['check_id'], unique=False)
    op.create_table('passages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=_dim()), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text) || to_tsvector('english', text)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_passages_embedding', 'passages', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_passages_embedding_model', 'passages', ['embedding_model'], unique=False)
    op.create_index('ix_passages_tsv', 'passages', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('verdicts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recheck_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_claim_id'), 'verdicts', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_claim_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index('ix_passages_tsv', table_name='passages', postgresql_using='gin')
    op.drop_index('ix_passages_embedding_model', table_name='passages')
    op.drop_index('ix_passages_embedding', table_name='passages', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('passages')
    op.drop_index(op.f('ix_stage_runs_check_id'), table_name='stage_runs')
    op.drop_table('stage_runs')
    op.drop_table('documents')
    op.drop_index('ix_claims_entity_keys', table_name='claims', postgresql_using='gin')
    op.drop_index('ix_claims_embedding', table_name='claims', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_claims_check_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('sources')
    op.drop_table('checks')
    # ### end Alembic commands ###
