"""claim review, rumour signals, rechecks

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 12:35:26.690310
"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('claim_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('verdicts', sa.Column('rechecked_from', sa.BigInteger(), nullable=True))
    op.add_column('verdicts', sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_verdicts_due', 'verdicts', ['recheck_at'], unique=False, postgresql_where=sa.text('superseded_at IS NULL'))
    op.create_foreign_key('fk_verdicts_rechecked_from', 'verdicts', 'verdicts', ['rechecked_from'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_verdicts_rechecked_from', 'verdicts', type_='foreignkey')
    op.drop_index('ix_verdicts_due', table_name='verdicts', postgresql_where=sa.text('superseded_at IS NULL'))
    op.drop_column('verdicts', 'superseded_at')
    op.drop_column('verdicts', 'rechecked_from')
    op.drop_column('documents', 'claim_review')
    op.drop_column('claims', 'signals')
    # ### end Alembic commands ###
