"""claims post_date

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 12:46:31.506745
"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('post_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'post_date')
    # ### end Alembic commands ###
