"""rate limit hits

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 16:34:40.314745
"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('identity', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_hits_identity_at', 'rate_limit_hits', ['identity', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_hits_identity_at', table_name='rate_limit_hits')
    op.drop_table('rate_limit_hits')
    # ### end Alembic commands ###
